package database

const (
	cVerificationTokensTableName = "verification_tokens"
	cUserTableName               = "users"
	cPollTableName               = "polls"
	cQuestionTableName           = "questions"
	cOptionTableName             = "options"
	cVoteTableName               = "votes"
	cParticipantTableName        = "participants"
	cPK                          = "ID"
	cID                          = "id"
	cEmail                       = "email"
	cToken                       = "token"
	cDisplayName                 = "display_name"
	cDeviceType                  = "device_type"
	cDeviceGUID                  = "device_guid"
	cCreatorID                   = "creator_id"
	cCreationDate                = "creation_date"
	cLastUpdated                 = "last_updated"
	cTitle                       = "title"
	cPollID                      = "poll_id"
	cQuestionID                  = "question_id"
	cValue                       = "value"
	cOptionalID                  = "optional_id"
	cOptionID                    = "option_id"
	cUserID                      = "user_id"
)
